### ISSUE TITLE
different lisp-let macro

### ISSUE THREAD

**Issue by dwoodlock** [Nappa9693/elfenben#5]
I like the idea of having a lisp-let macro like you put in the documentation:
(macro lisp-let (names vals rest...) ((function ~names ~rest...) ~@vals))
But it's a little hard to read since the names and the values are so separate:
(lisp-let (x y z) (5 6 7) (+ x y z))

So I was trying to write on where the names and values come next to each as in the var special form.  Example usage:
(lisp-let2 (x 5 y 6 z 7) (+ x y z))
But I'm having trouble doing it through the macro system. I assume I would like my resulting elf code to look like this:
(do (var x 5 y 6 z 7) (+ x y z))
So I tried a macro like this:
(macro lisp-let2 (namesvals rest...) (do (var ~namesvals) ~rest))  
But I get a syntax error because it's evaluating the list (x 5 y 6 z 7) and trying to use x as a function. I couldn't find a 'quote' special form or a ` that some lisps have.  I don't really know the macros syntax so there is probably a way to do this.  Any guidance?

**Comment by Nappa9693** [comment]
This should do the trick:

```
(macro lisp-let2 (nameVals rest...)
    (do
        (var ~@nameVals)
        ~rest...))
```

This will allow you to use the desired syntax of:
`(lisp-let2 (x 5 y 6 z 7) (+ x y z))`

Note that the `~@` syntax will translate `(x 5 y 6 z 7)` to literal `x 5 y 6 z 7` without evaluating the x. I will update the documentation (still a work in progress) as well regarding macros.

**Comment by dwoodlock** [comment]
That worked great.  btw - I'm trying to create a clojurescript like environment using your library + mori.  So far, while less powerful, it's been so much better than the real clojurescript environment for me - it's faster to develop and the javascript looks much better (for debugging).  Thanks for your project and let me know if you'd like me to share what I'm doing.

**Comment by Nappa9693** [comment]
I am happy that you are finding good use for Elfenben. Feel free to share what you are doing and also let me know if there is anything you would like to see added/changed/etc. to Elfenben.

**Comment by dwoodlock** [comment]
So I like the lisp concept applied to Javascript.  I like lispyscript and I like that you've picked it up and are enhancing it. But I also like the concept of immutable objects and I'm familiar with ClojureScript so I have been building enough of ClojureScript syntax through writing macros to implement the app that I'm working on.  And I also don't like mutable objects so I disallowed using Set and I implemented assoc from ClojureScript on plain js objects (by just copying).  You can see a small express app I build here in your language.  On top is the clojureScript things - I implemented def, defn, fn, let, and, or, ->, and assoc.  Take look: https://github.com/dwoodlock/gegirlstechnode.  

Let me know what you think.

**Comment by Nappa9693** [comment]
I think that its awesome! I like what you have done with mori and the macros to create your own syntax. Can't wait to see how this project develops :)
